version: "3" 

services:
  postgres:
    image: postgres
    container_name: banco-de-dados
    environment:
      POSTGRES_USER: barbershop
      POSTGRES_PASSWORD: barbershop
      POSTGRES_DB: barbershop
    ports:
      - 5432:5432

  app: 
    container_name: barber
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - postgres
    ports:
      - 3333:3333
