version: "3" 

services:
  app: 
    env_file:
      - .env
    build: .
    ports:
      - 3333:3333
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: barbershop
      POSTGRES_PASSWORD: barbershop
      POSTGRES_DB: barbershop
    ports:
      - 5432:5432
