version: "3.8" 

services:
  db:
    image: mysql:8.0.1
    command: --max_allowed_packet=32505856
    container_name: db-barber
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      MYSQL_DATABASE: barbershop
      MYSQL_ROOT_PASSWORD: pass
    ports:
      - 3306:3306
    expose:
      - 3306
    networks:
      - barber
  app:
    build: .
    command: sh -c "sleep 20 && npm run prisma:migrate && npm run dev"
    container_name: app-barber
    depends_on:
      - db
    ports:
      - 3000:3000
    expose:
      - 3000
    env_file:
      - .env
    links:
      - db
    volumes:
      - .:/usr/app
    networks:
      - barber
volumes:
  app:
    driver: local
networks:
  barber:
    driver: bridge